version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  smtp:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  web:
    build:
      target: development
    image: web-api
    mem_limit: 2g
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
      - redis
